Mar3hc/feat/write data by name
test-fullautomation/robotframework-uds pull request #24
Opened 2024-10-01 14:01 UTC by trimai3001

2024-10-02 02:16 UTC, ngoan1608 requested changes
Hi @trimai3001 ,

Please refer my review finding and provide the proper updates.

Thank you,
Ngoan

2024-10-02 02:16 UTC, ngoan1608 commented on test/example.robot
> +    Write Data By Name    RealTimeClock_Write    ${PARAM_DICT}
Hi Tri,

Please also add the test case for keyword `Write Data By Identifier` as we discussed.

Thank you,
Ngoan

2024-10-02 02:16 UTC, ngoan1608 commented on test/example.robot
> +${PARAM_STR}=    Day=26, Month=September, Year=2024, Hour=10, Second=45, Minute=0
This `${PARAM_STR}` is not used, consider to remove it

2024-10-02 02:16 UTC, ngoan1608 commented on RobotFramework_UDS/UDSKeywords.py
> +        SID_RQ = 46 # The request id of read data by identifier
`SID = 46` is write data, not read

2024-10-02 06:31 UTC, test-fullautomation requested changes
Hi Tri,

I wait till you commit the changes requested by Ngoan.

Thank you,
 Thoma

2024-10-02 09:18 UTC, trimai3001 commented
Hi Thomas,

I've resolved all of Ngoan's review findings. Please let me know if I missed anything.

Thank you,
Tri

2024-10-03 04:20 UTC, ngoan1608 approved these changes

2024-10-04 09:32 UTC, test-fullautomation approved these changes
Hi Tri,
very good!
Thank you,
 Thomas

2024-10-04 09:32 UTC, merged