Mar3hc/feat/general keyword to send and receive uds service
test-fullautomation/robotframework-uds pull request #34
Opened 2024-11-01 10:06 UTC by trimai3001

Add keyword Send UDS Request By Name for issue [https://github.com/test-fullautomation/robotframework-uds/issues/33], waiting for testing with DUT.

2024-11-11 11:25 UTC, trimai3001 commented
Hi @test-fullautomation,
This PR includes the solutions to the issue https://github.com/test-fullautomation/robotframework-uds/issues/31 and https://github.com/test-fullautomation/robotframework-uds/issues/33.
Thank you,
Tri

2024-11-11 11:55 UTC, test-fullautomation requested changes
Hi Tri,
please check my finding.
Thank you,
 Thomas

2024-11-11 11:55 UTC, test-fullautomation commented on config/robotframework_aio/release_items_RobotFramework_UDS.json
> +                      "0.13.2." : [
Hi Tri,
please change this to 0.13.1.
As I still wait for Son, I will merge it into 0.13.1.

Thank you,
 Thomas

2024-11-12 07:46 UTC, test-fullautomation approved these changes
Hi Tri,
this pull-request make #32 obsolete? Can I close #32?
Thank you,
 Thomas

2024-11-14 10:44 UTC, merged